services:
  app:
    build: .
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    volumes:
      - .:/user/app/src
    depends_on: [mysql]
    networks: [ps_network]

  mysql:
    image: mysql:8.4.2
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # volumes:
    #   - ./db/data:/var/lib/mysql
    networks: [ps_network]

networks:
  ps_network:
    driver: bridge
